// @ts-nocheck
import './style.css';
import './detail.css';

const RESULTLINE_CONTRACT_ADDRESS = '0x9877d9af48565797F71dA4492f5e4C8e44c944Cb' as const;
const CONFIG = {
  network: 'StudioNet / studionet', chainId: 61999,
  rpc: 'https://studio.genlayer.com/api',
  contract: RESULTLINE_CONTRACT_ADDRESS,
  canonical: true,
} as const;

type Agreement = { id: number; state: string; proposition: string; position: string; stake: any; creator: string; counterparty: string; outcome_type: string; subject: string; category: string; evidence_count: number; resolution: string };
type Provider = { request(args: { method: string; params?: unknown[] }): Promise<any> };
const $ = (s: string) => document.querySelector<HTMLElement>(s)!;
const app = $('#app');

app.innerHTML = `<header class="top"><a class="brand" href="#explore">RESULT<span>LINE</span></a><nav><a href="#explore">Explore</a><a href="#how">How it works</a><button id="wallet" class="wallet">Connect wallet</button></nav></header>
<main><section id="explore" class="hero"><div class="beam"></div><p class="eyebrow">CONSTITUTION-BOUND AUTHORITATIVE EVENT RESOLUTION</p><h1>When the show ends,<br/><em>the contract knows.</em></h1><p class="lede">Two positions. One frozen source. A GenLayer verdict that settles what actually happened.</p><div class="hero-actions"><a class="btn acid" href="#create">Create a Resultline <b>↗</b></a><span class="network-pill">● ${CONFIG.network} · ${CONFIG.chainId}</span></div></section>
<section class="ticker"><span>LIVE STUDIONET TEST</span><span>LIVE AGREEMENTS</span><span>OFFICIAL EVIDENCE</span><span>SEMANTIC CONSENSUS</span><span>FINALITY, NOT FOMO</span></section>
<section class="section" id="agreements"><div class="section-head"><div><p class="eyebrow">THE BOARD</p><h2>Results in motion.</h2></div><span id="load-state" class="muted">Reading StudioNet…</span></div><div id="cards" class="tickets"></div></section>
<section id="create" class="create section"><div><p class="eyebrow">NEW AGREEMENT</p><h2>Freeze the question<br/><em>before the answer.</em></h2><p class="muted">The constitution is immutable once matched. Build a precise proposition, commit the official source, then let GenLayer resolve the evidence.</p></div><form id="create-form"><label>Proposition<input name="proposition" value="Anora won Best Picture at the 97th Academy Awards." required/></label><div class="grid2"><label>Subject<input name="subject" value="Anora" required/></label><label>Category<input name="category" value="Best Picture" required/></label></div><div class="grid2"><label>Official host<input name="host" value="www.oscars.org" required/></label><label>Path<input name="path" value="/oscars/ceremonies/2025" required/></label></div><label>Stake (GEN)<input name="stake" type="number" min="0.001" step="0.001" value="0.001" required/></label><div class="review">IMMUTABLE REVIEW <span>Source rules lock at match. Protocol fees are separate from stake.</span></div><button class="btn acid" type="button" id="prepare">Prepare with wallet <b>→</b></button><p id="form-status" class="status"></p></form></section>
<section id="how" class="how section"><p class="eyebrow">WHY GENLAYER</p><h2>Messy reality needs<br/><em>meaningful consensus.</em></h2><div class="how-grid"><article><b>01 / PRECOMMIT</b><h3>Constitution</h3><p>Host, path, event, timing and positions are frozen before matching.</p></article><article><b>02 / FREEZE</b><h3>Evidence</h3><p>The official page is rendered into bounded, untrusted evidence.</p></article><article><b>03 / RESOLVE</b><h3>Verdict</h3><p>Independent validators compare structured semantic assessments.</p></article></div></section></main><footer><span>RESULTLINE / ELECTRIC VERDICT</span><span>${CONFIG.network} · ${CONFIG.chainId}</span></footer>`;

const provider = (): Provider | undefined => (window as any).ethereum;
let activeAccount: `0x${string}` | undefined;
const STUDIO_NET = { chainId: '0xf26f', chainName: 'StudioNet', nativeCurrency: { name: 'GEN', symbol: 'GEN', decimals: 18 }, rpcUrls: [CONFIG.rpc], blockExplorerUrls: ['https://explorer-studio.genlayer.com/'] };
const ensureStudioNet = async (p: Provider) => {
  const current = Number(await p.request({method:'eth_chainId'}));
  if (current === CONFIG.chainId) return true;
  try { await p.request({method:'wallet_switchEthereumChain', params:[{chainId: STUDIO_NET.chainId}]}); }
  catch (e: any) {
    const detail = String(e?.message || e);
    if (e?.code !== 4902 && !/same RPC endpoint|already exists|already added/i.test(detail)) throw e;
    if (e?.code === 4902) await p.request({method:'wallet_addEthereumChain', params:[STUDIO_NET]});
    await p.request({method:'wallet_switchEthereumChain', params:[{chainId: STUDIO_NET.chainId}]});
  }
  return Number(await p.request({method:'eth_chainId'})) === CONFIG.chainId;
};
const showNetworkState = (chain: number, account?: string) => { const wallet = document.querySelector<HTMLElement>('#wallet'); if (wallet) wallet.textContent = chain === CONFIG.chainId && account ? `${account.slice(0,6)}…${account.slice(-4)} · StudioNet` : 'Switch to StudioNet'; const status = document.querySelector<HTMLElement>('#form-status'); if (status && chain !== CONFIG.chainId) status.textContent = `Wrong network — switch to StudioNet (${CONFIG.chainId})`; };
const CONTRACT_METHODS = ['create_agreement','match_agreement','cancel_agreement','freeze_evidence','resolve','settle','withdraw','get_agreement','get_agreement_count','get_evidence','get_withdrawable'];
const parseRecord = (value: any) => { if (typeof value !== 'string') return value; return Object.fromEntries(value.split('|').map((part: string) => { const i=part.indexOf('='); return i<0 ? [part,''] : [part.slice(0,i),part.slice(i+1)]; })); };
const rpc = async (method: string, params: unknown[] = []) => { const res = await fetch(CONFIG.rpc, {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})}); const json = await res.json(); if(json.error) throw new Error(json.error.message ?? 'RPC error'); return json.result; };
const validContractAddress = (address: unknown): address is `0x${string}` => typeof address === 'string' && /^0x[0-9a-fA-F]{40}$/.test(address) && address.toLowerCase() === RESULTLINE_CONTRACT_ADDRESS.toLowerCase();
const diagnostic = (readState: string) => { const el=$('#form-status'); el.textContent=`CHAIN: ${CONFIG.chainId} · STUDIONET RPC: CONNECTED · CONTRACT ADDRESS: ${RESULTLINE_CONTRACT_ADDRESS} · CONTRACT READ: ${readState}`; };
const read = async (method: string, args: unknown[] = []) => {
  if (!validContractAddress(CONFIG.contract)) throw new Error(`Invalid RESULTLINE contract configuration: ${String(CONFIG.contract)}`);
  const { createClient } = await import('https://esm.sh/genlayer-js@1.1.8');
  const { studionet } = await import('https://esm.sh/genlayer-js@1.1.8/chains');
  const client = createClient({ chain: studionet });
  return parseRecord(await (client as any).readContract({ address: RESULTLINE_CONTRACT_ADDRESS, functionName: method, args }));
};
const renderCards = (items: Agreement[]) => { $('#cards').innerHTML = items.length ? items.map(a => `<article class="ticket" tabindex="0" data-id="${a.id}"><div class="ticket-top"><span class="state ${a.state.toLowerCase()}">${a.state}</span><span class="mono">#${a.id.toString().padStart(3,'0')}</span></div><h3>${a.proposition}</h3><div class="ticket-meta"><span>${a.subject} · ${a.category}</span><strong>${a.position}</strong></div><div class="ticket-foot"><span>${a.stake} GEN stake</span><span class="source">SOURCE STRIP · ${a.evidence_count ? 'FROZEN' : 'PRECOMMITTED'}</span></div></article>`).join('') : '<div class="empty">No agreements indexed yet. Create the first precise question.</div>'; document.querySelectorAll<HTMLElement>('[data-id]').forEach(x=>x.onclick=()=>location.hash=`agreement/${x.dataset.id}`); };
const client = async () => { const { createClient } = await import('https://esm.sh/genlayer-js@1.1.8'); const { studionet } = await import('https://esm.sh/genlayer-js@1.1.8/chains'); if(!activeAccount) throw new Error('Connect wallet first'); return createClient({chain:studionet, account:activeAccount, provider:provider()!} as any); };
const submitWrite = async (method: string, args: unknown[], value = 0n) => { if(!activeAccount) throw new Error('Connect wallet first'); if(!validContractAddress(CONFIG.contract)) throw new Error('Invalid RESULTLINE contract configuration'); const c=await client(); $('#form-status').textContent=`AWAITING WALLET APPROVAL · stake ${value} wei · protocol fees handled by StudioNet`; const txId=await c.writeContract({account:activeAccount,address:RESULTLINE_CONTRACT_ADDRESS,functionName:method,args,value}); $('#form-status').textContent=`SUBMITTED ${txId} · INSPECTING CONSENSUS`; const tx=await c.waitForTransactionReceipt({hash:txId}); $('#form-status').textContent=`${String(tx.statusName||tx.status||'RECEIPT').toUpperCase()} · ${String(tx.txExecutionResultName||'EXECUTION RECORDED')}`; await load(); return tx; };
const detail = async (id:number) => { const a:Agreement=await read('get_agreement',[id]); const evidence=[]; for(let i=0;i<Number(a.evidence_count);i++) evidence.push(await read('get_evidence',[i])); $('#agreements').innerHTML=`<div class="detail"><a href="#explore">← Back to board</a><p class="eyebrow">AGREEMENT #${id}</p><h2>${a.proposition}</h2><div class="detail-grid"><div><b>STATE</b><strong>${a.state}</strong><b>OUTCOME</b><strong>${a.outcome_type}</strong><b>POSITION</b><strong>${a.position}</strong><b>STAKE / POT</b><strong>${a.stake} / ${a.stake*2} GEN</strong></div><div><b>SUBJECT / CATEGORY</b><strong>${a.subject} · ${a.category}</strong><b>CREATOR</b><strong class="mono">${a.creator}</strong><b>COUNTERPARTY</b><strong class="mono">${a.counterparty}</strong><b>RESOLUTION</b><strong>${a.resolution||'Pending'}</strong></div></div><div class="evidence-list">${evidence.map((e:any)=>`<article><span class="eyebrow">FROZEN EVIDENCE #${e.id}</span><p>${e.text}</p><a href="${e.url}" target="_blank" rel="noreferrer">${e.url}</a></article>`).join('')||'<p class="muted">Evidence has not been frozen.</p>'}</div><div class="actions">${a.state==='OPEN'&&activeAccount&&activeAccount.toLowerCase()!==String(a.creator).toLowerCase()?'<button class="btn acid" id="match">Match agreement</button>':''}${a.state==='OPEN'&&activeAccount&&activeAccount.toLowerCase()===String(a.creator).toLowerCase()?'<button class="btn" id="cancel">Cancel agreement</button>':''}${a.state==='MATCHED'?'<button class="btn acid" id="freeze">Freeze official evidence</button>':''}${a.state==='EVIDENCE_FROZEN'?'<button class="btn acid" id="resolve">Resolve with GenLayer</button>':''}${a.state==='RESOLVED'?'<button class="btn acid" id="settle">Settle agreement</button>':''}${a.state==='SETTLED'?'<button class="btn acid" id="withdraw">Withdraw winnings</button>':''}</div></div>`; const bind=(id:string,m:string,args:unknown[],v=0n)=>{const b=document.querySelector<HTMLButtonElement>('#'+id);if(b)b.onclick=()=>submitWrite(m,args,v).catch(e=>$('#form-status').textContent=e.message)}; bind('match','match_agreement',[id, a.creator_position === 'YES' ? 'NO' : 'YES'],BigInt(a.stake)); bind('cancel','cancel_agreement',[id]); bind('freeze','freeze_evidence',[id,'https://www.oscars.org/oscars/ceremonies/2025']); bind('resolve','resolve',[id]); bind('settle','settle',[id]); bind('withdraw','withdraw',[]); };
async function load() { try { const count = Number(await read('get_agreement_count')); const rows: Agreement[] = []; for(let i=0;i<Math.min(count,12);i++) rows.push(await read('get_agreement',[i])); renderCards(rows); $('#load-state').textContent = `${count} agreement${count===1?'':'s'} · authoritative read`; } catch(e) { $('#load-state').textContent = 'StudioNet read unavailable'; $('#cards').innerHTML = '<div class="empty">Authoritative reads are unavailable. No demo data is substituted.</div>'; } }
window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#agreement\/(\d+)/); if(m) detail(Number(m[1])).catch(e=>$('#load-state').textContent=e.message); else load();});
$('#wallet').onclick = async () => { const p=provider(); if(!p){$('#wallet').textContent='Install an EIP-1193 wallet';return;} try { const [a]=await p.request({method:'eth_requestAccounts'}); if(!await ensureStudioNet(p)) throw new Error(`Wrong network — switch to StudioNet (${CONFIG.chainId})`); activeAccount=a; showNetworkState(CONFIG.chainId,a); if(location.hash.startsWith('#agreement/')) location.hash=location.hash; } catch(e:any) { const chain=Number(await p.request({method:'eth_chainId'})); showNetworkState(chain); $('#form-status').textContent=e.message; } };
(window as any).ethereum?.on?.('accountsChanged', (accounts: string[]) => { activeAccount=accounts[0]; const chain=Number((window as any).ethereum.chainId); showNetworkState(chain,activeAccount); });
(window as any).ethereum?.on?.('chainChanged', (value: string) => { const chain=Number(value); showNetworkState(chain,activeAccount); });
$('#prepare').onclick = async () => { const p=provider(); if(!p){$('#form-status').textContent='Connect an EIP-1193 wallet first.';return;} try { const [a]=await p.request({method:'eth_accounts'}); if(!a?.length){await ($('#wallet') as HTMLButtonElement).click();return;} if(!await ensureStudioNet(p)) throw new Error(`Wrong network — switch to StudioNet (${CONFIG.chainId})`); activeAccount=a; showNetworkState(CONFIG.chainId,activeAccount); if(!validContractAddress(CONFIG.contract)){diagnostic('FAIL — invalid address');return;} diagnostic('CHECKING'); try { await read('get_agreement_count'); } catch(e:any) { diagnostic(`FAIL — ${e.message}`); return; } diagnostic('PASS'); const f=new FormData(document.querySelector<HTMLFormElement>('#create-form')!); const now=Math.floor(Date.now()/1000), close=now+7200, notBefore=close+300, deadline=notBefore+7200; const args=['AWARD_WINNER',f.get('proposition'),f.get('subject'),f.get('category'),'Academy of Motion Picture Arts and Sciences','97th Academy Awards',f.get('host'),f.get('path'),'YES','POST_EVENT_VERIFICATION',close,1740873600,notBefore,deadline]; const stake=BigInt(Math.round(Number(f.get('stake'))*1e18)); await submitWrite('create_agreement',args,stake); } catch(e:any) { diagnostic(`FAIL — ${e.message}`); } };
load();
